### ISSUE TITLE
state-hoisting

### ISSUE THREAD

**Issue by josemontecastelo** [DantePereyra/dailyplanner#1]
https://github.com/DantePereyra/dailyplanner/blob/eb024dd79770c69d752cc41b9e840cc72d45bf5f/app/src/main/java/com/dantepereyra/dailyplanner/MainActivity.kt#L79

Como práctica recomendada, no se debe pasar el viewmodel a composables mas pequeños, se debe extraer el estado en el primero composable padre y partir de ahí pasar a los composables solo el estado que necesitas dibujar.

https://developer.android.com/jetpack/compose/state-hoisting

En tu caso, obtendrías la lista de tasks dentro del composable `DailyPlannerApp` y a partir de ahí dejarías de utilizar el view model enviando como parámetro la lista.

**Comment by DantePereyra** [comment]
Ya está hecho el cambio, extraigo la lista directamente en el composable padre y la paso a los composables más pequeños.
