### ISSUE TITLE
No utilizar el mismo nombre de variable para las diferentes rutas

### ISSUE THREAD

**Issue by josemontecastelo** [DantePereyra/dailyplanner#2]
https://github.com/DantePereyra/dailyplanner/blob/825dab2b61357202e17c02150a796d8d2ee3258a/app/src/main/java/com/dantepereyra/dailyplanner/features/task/TaskScreenNavigation.kt#L10

Recomiendo no utilizar el mismo nombre de variable para evitar confusiones y problemas.

**Comment by DantePereyra** [comment]
Actualizado para cada ruta
