### ISSUE TITLE
Extraer DailyPlannerAplication a un archivo a parte

### ISSUE THREAD

**Issue by josemontecastelo** [DantePereyra/dailyplanner#4]
https://github.com/DantePereyra/dailyplanner/blob/825dab2b61357202e17c02150a796d8d2ee3258a/app/src/main/java/com/dantepereyra/dailyplanner/MainActivity.kt#L152C7-L152C29

La clase Aplication debería estar en un archivo aparte, en tu caso DailyPlannerAplication.kt

**Comment by DantePereyra** [comment]
Actualizado para usar DailyPlannerAplication.kt
