### ISSUE TITLE
No funciona navegación

### ISSUE THREAD

**Issue by josemontecastelo** [DantePereyra/dailyplanner#5]
https://github.com/DantePereyra/dailyplanner/blob/825dab2b61357202e17c02150a796d8d2ee3258a/app/src/main/java/com/dantepereyra/dailyplanner/MainActivity.kt#L65

La navegación no funciona porque estás utilizando dos tipos diferentes de `navController`, uno en `MainActivity` y otro en `Navigation`
Si necesitas el navController mas arriba, deberás pasarlo por parámetro hasta llegar a Navigation.

**Comment by DantePereyra** [comment]
Ya funciona correctamente, además de volver a la pantalla de inicio tras añadir la tarea.
